### ISSUE TITLE
Offset is unspecified

### ISSUE THREAD

**Issue by akardas16** [Hukumister/LazyCardStack#12]
Hi, when I add library as module in my project, I am getting `Offset is unspecified`.
```
Exception dispatching input event.
Exception in MessageQueue callback: handleReceiveCallback
java.lang.IllegalStateException: Offset is unspecified
	at androidx.compose.ui.geometry.InlineClassHelperKt.throwIllegalStateException(InlineClassHelper.kt:35)
	at androidx.compose.ui.geometry.OffsetKt.isFinite-k-4lQ0M(Offset.kt:364)
	at androidx.compose.ui.node.NodeCoordinator.withinLayerBounds-k-4lQ0M(NodeCoordinator.kt:1036)
	at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:522)
	at androidx.compose.ui.node.LayoutNode.hitTest-M_7yMNQ$ui_release(LayoutNode.kt:986)
	at androidx.compose.ui.node.NodeCoordinator$Companion$PointerInputSource$1.childHitTest-YqVAtuI(NodeCoordinator.kt:1267)
	at androidx.compose.ui.node.InnerNodeCoordinator.hitTestChild-YqVAtuI(InnerNodeCoordinator.kt:220)
	at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:542)
	at androidx.compose.ui.node.NodeCoordinator.hitTestChild-YqVAtuI(NodeCoordinator.kt:694)
	at androidx.compose.ui.node.NodeCoordinator.hit-1hIXUjU(NodeCoordinator.kt:594)
	at androidx.compose.ui.node.NodeCoordinator.access$hit-1hIXUjU(NodeCoordinator.kt:57)
	at androidx.compose.ui.node.NodeCoordinator$hit$1.invoke(NodeCoordinator.kt:598)
	at androidx.compose.ui.node.NodeCoordinator$hit$1.invoke(NodeCoordinator.kt:596)
	at androidx.compose.ui.node.HitTestResult.hitInMinimumTouchTarget(HitTestResult.kt:117)
	at androidx.compose.ui.node.HitTestResult.hit(HitTestResult.kt:97)
	at androidx.compose.ui.node.NodeCoordinator.hit-1hIXUjU(NodeCoordinator.kt:596)
	at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
	at androidx.compose.ui.node.LayoutNode.hitTest-M_7yMNQ$ui_release(LayoutNode.kt:986)
	at androidx.compose.ui.node.NodeCoordinator$Companion$PointerInputSource$1.childHitTest-YqVAtuI(NodeCoordinator.kt:1267)
	at androidx.compose.ui.node.InnerNodeCoordinator.hitTestChild-YqVAtuI(InnerNodeCoordinator.kt:220)
	at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:542)
	at androidx.compose.ui.node.NodeCoordinator.hitTestChild-YqVAtuI(NodeCoordinator.kt:694)
	at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:542)
	at androidx.compose.ui.node.NodeCoordinator.hitTestChild-YqVAtuI(NodeCoordinator.kt:694)
	at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:542)
	at androidx.compose.ui.node.LayoutNode.hitTest-M_7yMNQ$ui_release(LayoutNode.kt:986)
	at androidx.compose.ui.node.NodeCoordinator$Companion$PointerInputSource$1.childHitTest-YqVAtuI(NodeCoordinator.kt:1267)
	at androidx.compose.ui.node.InnerNodeCoordinator.hitTestChild-YqVAtuI(InnerNodeCoordinator.kt:220)
	at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:542)
	at androidx.compose.ui.node.NodeCoordinator.hitTestChild-YqVAtuI(NodeCoordinator.kt:694)
	at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:542)
	at androidx.compose.ui.node.NodeCoordinator.hitTestChild-YqVAtuI(NodeCoordinator.kt:694)
	at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:542)
	at androidx.compose.ui.node.NodeCoordinator.hitTestChild-YqVAtuI(NodeCoordinator.kt:694)
	at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:542)
	at androidx.compose.ui.node.LayoutNode.hitTest-M_7yMNQ$ui_release(LayoutNode.kt:986)
	at androidx.compose.ui.node.NodeCoordinator$Companion$PointerInputSource$1.childHitTest-YqVAtuI(NodeCoordinator.kt:1267)
	at androidx.compose.ui.node.InnerNodeCoordinator.hitTestChild-YqVAtuI(InnerNodeCoordinator.kt:220)
```

**Comment by Hukumister** [comment]
Hi, can you attach some sample code for how you use the library?

**Comment by akardas16** [comment]
> Hi, can you attach some sample code for how you use the library?

you can check https://github.com/akardas16/LazyCardStackSample repository. After you run project and try to swipe card, error will occur, and app will crash.

**Comment by NaveenPokhriyal** [comment]
@akardas16 check if you have define the composition for  LocalComposeWindow.
check the implementation in [androidMain](https://github.com/Hukumister/LazyCardStack/blob/master/sample/shared/src/androidMain/kotlin/com/haroncode/sample/ui/ComposeApp.kt) & [iosMain](https://github.com/Hukumister/LazyCardStack/blob/master/sample/shared/src/iosMain/kotlin/ComposeApp.kt)

**Comment by akardas16** [comment]
> @akardas16 check if you have define the composition for LocalComposeWindow. check the implementation in [androidMain](https://github.com/Hukumister/LazyCardStack/blob/master/sample/shared/src/androidMain/kotlin/com/haroncode/sample/ui/ComposeApp.kt) & [iosMain](https://github.com/Hukumister/LazyCardStack/blob/master/sample/shared/src/iosMain/kotlin/ComposeApp.kt)

thank you so much. I didn't see that part.
